version: '3.5'

services:
  crawler:
    container_name: ebk-ml-crawler
    image: nicoenking/ebk-ml-crawler
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - postgres
    restart: unless-stopped
    cap_add:
      - "SYS_ADMIN"

  postgres:
    container_name: ebk-ml-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: ebk-ml-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      VIRTUAL_HOST: ebk-ml-pgadmin.enking.dev
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ebk-ml-pgadmin.enking.dev
      LETSENCRYPT_EMAIL: nico.enking@gmail.com
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
      - nginx
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  nginx:
    name: nginx
    external: true

volumes:
    postgres:
    pgadmin: